# Learn R for Statistics
## Section 2: Data and Programming
### 1. Data types

R has a number of basic data types
- Numeric (Double)
- Integer
- Complex
- Logical
- Character

In [2]:
10.1 
30L
4 + 2i
TRUE
"Statistics"

[1] 10.1

[1] 30

[1] 4+2i

[1] TRUE

[1] "Statistics"

### 2. Data structures
R also has a number of basic data structures. A data structure is either homogeneous (all elements are of the same data type) or heterogeneous (elements can be of more than one data type).

#### 2.1 Vectors
Data structure that store element of the same type. Many operations in R make heavy use of vectors. Vectors in R are indexed
starting at 1. Larger vectors will start additional rows with [*] where * is the index of the first element of the row.

##### To create a vector there are four ways:
- c()
- :
- seq()
- rep()

###### Use c()

In [3]:
c(1,3,5,7,8,9)

[1] 1 3 5 7 8 9

Can store to a variable using assignment operator = or <-

Not much difference between the two, but should stay consistent

In [10]:
x = c(1,3,5,7,8,9)
y <- c(4,2,1)
y
x[1]

[1] 4 2 1

[1] 1

R will automatically coerce to a single type when attempting to create a vector combines multiple types

In [19]:
c(42, "Statistics", TRUE)
c(32, FALSE)
c(4+2i, 20, 30L)

[1] "42"         "Statistics" "TRUE"

[1] 32  0

[1]  4+2i 20+0i 30+0i

###### Use : and seq()
Create vector based on a sequence of number

In [21]:
(y = 1:100)

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [23]:
seq(from = 2.1, to = 2.2, by = 0.01)
seq(2.1, 2.2, 0.01)

[1] 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19 2.20

[1] 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19 2.20

###### Use rep()
Can use to repeat a vector by a number of times

In [27]:
rep("A", times = 10)
rep("B", 2)
rep(x,2)

[1] "A" "A" "A" "A" "A" "A" "A" "A" "A" "A"

[1] "B" "B"

[1] 1 3 5 7 8 9 1 3 5 7 8 9

###### Combine methods
So far we have mostly used them in isolation, but they are often used together.

In [28]:
c(x, rep(seq(1, 9, 2), 3), c(1, 2, 3), 42, 2:4)

[1]  1  3  5  7  8  9  1  3  5  7  9  1  3  5  7  9  1  3  5  7  9  1  2  3 42
[26]  2  3  4

##### Length
The length of a vector can be obtained with the length() function.

In [29]:
length(x)
length(y)

[1] 6

[1] 100

##### Subsetting
To subset a vector, use square brackets [ ]

In [31]:
x
x[1]
x[-2] #exclude second element

#subset based on vector of indices:
x[1:3] 
x[c(1,3,4)]
z = c(TRUE,TRUE,FALSE,TRUE,TRUE,FALSE)
x[z]

[1] 1 3 5 7 8 9

[1] 1

[1] 1 5 7 8 9

[1] 1 3 5

[1] 1 5 7

[1] 1 3 7 8

##### Vectorization
One of the biggest stranths of R

In [32]:
x = 1:10
x + 1
2 * x
2 ^ x
sqrt(x)

[1]  2  3  4  5  6  7  8  9 10 11

[1]  2  4  6  8 10 12 14 16 18 20

[1]    2    4    8   16   32   64  128  256  512 1024

[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

##### Logical operators
Types:
- < / > : less than/greater than
- <= / >= : less/greater than or equal to
- == : equal to
- != : not equal to
- !x : not x
- x | y : x or y
- x & y : x and y

In R, logical operators are vectorized

In [33]:
x = c(1,3,5,7,8,9)
x > 3
x == 3
x != 3
x == 3 & x!= 3


[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1] FALSE  TRUE FALSE FALSE FALSE FALSE

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

[1] FALSE FALSE FALSE FALSE FALSE FALSE

This is useful for subsetting

In [41]:
x[x > 3]
x[x != 3]
sum(x > 3) 
#sum of all elements. Here R is auto-coercing logical to numeric
as.numeric( x > 3) 
which(x > 3) #return indices
x[which(x > 3)]
max(x)
which.max(x)

[1] 5 7 8 9

[1] 1 5 7 8 9

[1] 4

[1] 0 0 1 1 1 1

[1] 3 4 5 6

[1] 5 7 8 9

[1] 9

[1] 6

##### More vectorization


In [42]:
x = c(1, 3, 5, 7, 8, 9)
y = 1:100

In [43]:
x + y

Warning message in x + y:
"longer object length is not a multiple of shorter object length"

[1]   2   5   8  11  13  15   8  11  14  17  19  21  14  17  20  23  25  27
 [19]  20  23  26  29  31  33  26  29  32  35  37  39  32  35  38  41  43  45
 [37]  38  41  44  47  49  51  44  47  50  53  55  57  50  53  56  59  61  63
 [55]  56  59  62  65  67  69  62  65  68  71  73  75  68  71  74  77  79  81
 [73]  74  77  80  83  85  87  80  83  86  89  91  93  86  89  92  95  97  99
 [91]  92  95  98 101 103 105  98 101 104 107

R is auto-coercing

In [44]:
y = 1:60
x + y

[1]  2  5  8 11 13 15  8 11 14 17 19 21 14 17 20 23 25 27 20 23 26 29 31 33 26
[26] 29 32 35 37 39 32 35 38 41 43 45 38 41 44 47 49 51 44 47 50 53 55 57 50 53
[51] 56 59 61 63 56 59 62 65 67 69

In [58]:
all(x + y == rep(x, 10) + y)
#return whether all of logical vectors in this are true
identical(x + y, rep(x, 10) + y)
#test if two objects are identical

[1] TRUE

[1] TRUE

#### 2.2 Matrices
Matrices have rows and columns containing a single data type. In a matrix, the order of rows and columns is important.

##### Create matrix
Matrices can be created using the matrix function.

In [60]:
x = 1:9
X = matrix(x, nrow = 3, ncol = 3)
X

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

By default the matrix function reorders a vector into columns, but we can also tell R to use rows instead

In [61]:
Y = matrix(x, nrow = 3, ncol = 3, byrow = TRUE)
Y

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

Create a matrix where every element is the same 

In [63]:
Z = matrix(0, 3, 2)
Z

[,1] [,2]
[1,] 0    0   
[2,] 0    0   
[3,] 0    0

##### Subsetting 
Using [ ] with specifying row and column

In [65]:
X
X[1,2]
X[1,]
X[,2]

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 4

[1] 1 4 7

[1] 4 5 6

Can subset more than one row or column at a time

In [66]:
X[2, c(1, 3)]

[1] 2 8

##### Combining

In [67]:
x = 1:9
rev(x) # reverse vector
rep(1,9)

[1] 9 8 7 6 5 4 3 2 1

[1] 1 1 1 1 1 1 1 1 1

- rbind: combine vectors to matrix where each is a row
- cbind: combine vectors to matrix where each is a column

Can specified argument names 

In [72]:
rbind(x, rev(x), rep(1, 9))
cbind(col_1 = x, col_2 = rev(x), col_3 = rep(1, 9)) 

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
x 1    2    3    4    5    6    7    8    9   
  9    8    7    6    5    4    3    2    1   
  1    1    1    1    1    1    1    1    1

col_1 col_2 col_3
 [1,] 1     9     1    
 [2,] 2     8     1    
 [3,] 3     7     1    
 [4,] 4     6     1    
 [5,] 5     5     1    
 [6,] 6     4     1    
 [7,] 7     3     1    
 [8,] 8     2     1    
 [9,] 9     1     1

 ##### Matrix calculation

In [1]:
X = matrix(1:9, 3, 3)
Y = matrix(9:1, 3, 3)
X
Y

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 9    6    3   
[2,] 8    5    2   
[3,] 7    4    1

In [2]:
X + Y
X - Y
X * Y # element by element multiplication
X / Y

[,1] [,2] [,3]
[1,] 10   10   10  
[2,] 10   10   10  
[3,] 10   10   10

[,1] [,2] [,3]
[1,] -8   -2   4   
[2,] -6    0   6   
[3,] -4    2   8

[,1] [,2] [,3]
[1,]  9   24   21  
[2,] 16   25   16  
[3,] 21   24    9

[,1]      [,2]      [,3]    
[1,] 0.1111111 0.6666667 2.333333
[2,] 0.2500000 1.0000000 4.000000
[3,] 0.4285714 1.5000000 9.000000

In [3]:
X %*% Y #Matrix multiplication

[,1] [,2] [,3]
[1,]  90  54   18  
[2,] 114  69   24  
[3,] 138  84   30

In [4]:
t(X) #transpose

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [6]:
Z = matrix(c(9, 2, -3, 2, 4, -2, -3, -2, 16), 3, byrow = TRUE)
solve(Z) #inverse of a matrix (if it is invertible)

[,1]        [,2]        [,3]      
[1,]  0.12931034 -0.05603448 0.01724138
[2,] -0.05603448  0.29094828 0.02586207
[3,]  0.01724138  0.02586207 0.06896552

In [7]:
solve(Z) %*% Z

[,1]          [,2]          [,3]         
[1,]  1.000000e+00 -6.245005e-17  0.000000e+00
[2,]  8.326673e-17  1.000000e+00 -5.551115e-17
[3,] -2.775558e-17  0.000000e+00  1.000000e+00

In [8]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [9]:
all.equal(solve(Z) %*% Z, diag(3))

[1] TRUE

In [11]:
dim(Z) #dimension
rowSums(Z)
colSums(Z)
rowMeans(Z)
colMeans(Z)

[1] 3 3

[1]  8  4 11

[1]  8  4 11

[1] 2.666667 1.333333 3.666667

[1] 2.666667 1.333333 3.666667

diag() can extract diagonal of a matrix or create a diagonal matrix

In [13]:
diag(Z)
diag(1:3)
diag(3)

[1]  9  4 16

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

#### 2.3 Calculations with vectors and matrices

Some operations have different behavior on vectors and matrices.

Example: %*% on vector is inner product

In [15]:
a_vec = c(1,2,3)
b_vec = c(2,2,2)
c(is.vector(a_vec), is.vector(b_vec))

[1] TRUE TRUE

In [16]:
a_vec %*% b_vec 

[,1]
[1,] 12

%o% : outer product of 2 vectors

Important: when vector is coerced to become matrix, they are column vectors

In [23]:
as.matrix(a_vec)
a_vec %o% b_vec

[,1]
[1,] 1   
[2,] 2   
[3,] 3

[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 4    4    4   
[3,] 6    6    6

But in this case, b_vec is auto coerced to 1x3 matrix

In [24]:
as.matrix(a_vec) %*% b_vec

[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 4    4    4   
[3,] 6    6    6

Another way for inner and outer product

In [25]:
crossprod(a_vec, b_vec)
tcrossprod(a_vec, b_vec)

[,1]
[1,] 12

[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 4    4    4   
[3,] 6    6    6

When use this with matric, it calculates t(X).Y

This is really useful when using in linear models

In [27]:
C_mat = matrix(c(1, 2, 3, 4, 5, 6), 2, 3)
D_mat = matrix(c(2, 2, 2, 2, 2, 2), 2, 3)
crossprod(C_mat, D_mat)
t(C_mat) %*% D_mat

[,1] [,2] [,3]
[1,]  6    6    6  
[2,] 14   14   14  
[3,] 22   22   22

[,1] [,2] [,3]
[1,]  6    6    6  
[2,] 14   14   14  
[3,] 22   22   22

#### 2.4 Lists
One dimensional heterogeneous data structure (element of any type)


##### Creation
List can be in very complex form

In [28]:
list(42, "Hello", TRUE) 

[[1]]
[1] 42

[[2]]
[1] "Hello"

[[3]]
[1] TRUE

In [31]:
ex_list = list(
    a = c(1,2,3,4),
    b = TRUE,
    c = "Hello!",
    d = function(arg = 42) {print("Hello World")},
    e = diag(3)
    )

In [35]:
ex_list[1]
ex_list[2:3]
ex_list["e"]

$a
[1] 1 2 3 4

$b
[1] TRUE

$c
[1] "Hello!"

$e
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

In [42]:
ex_list$d
ex_list$d(arg = 2)

function(arg = 42) {print("Hello World")}
<bytecode: 0x000000000b9501f8>

[1] "Hello World"


#### 2.5 Data Frames
Data frame is a list of vectors, each vector contain the same data type but different vectors can store different data types

The elements of data frame must all be vectors, and have the same length

In [46]:
example_data = data.frame(x = c(1, 3, 5, 7, 9, 1, 3, 5, 7, 9),
                        y = c(rep("Hello", 9), "Goodbye"),
                        z = rep(c(TRUE, FALSE), 5))

In [47]:
example_data

x y       z    
1  1 Hello    TRUE
2  3 Hello   FALSE
3  5 Hello    TRUE
4  7 Hello   FALSE
5  9 Hello    TRUE
6  1 Hello   FALSE
7  3 Hello    TRUE
8  5 Hello   FALSE
9  7 Hello    TRUE
10 9 Goodbye FALSE

In [48]:
str(example_data)

'data.frame':	10 obs. of  3 variables:
 $ x: num  1 3 5 7 9 1 3 5 7 9
 $ y: Factor w/ 2 levels "Goodbye","Hello": 2 2 2 2 2 2 2 2 2 1
 $ z: logi  TRUE FALSE TRUE FALSE TRUE FALSE ...


In [50]:
nrow(example_data)
ncol(example_data)
dim(example_data)

[1] 10

[1] 3

[1] 10  3

#### Read data from file
Read csv file using read_csv().

In [51]:
library(readr)

In [53]:
example_data_from_csv = read_csv("D:/HUST/20212/Applied statistics and experimental design/Code/example-data.csv")
example_data_from_csv

Parsed with column specification:
cols(
  x = col_double(),
  y = col_character(),
  z = col_logical()
)


x y       z    
1  1 Hello    TRUE
2  3 Hello   FALSE
3  5 Hello    TRUE
4  7 Hello   FALSE
5  9 Hello    TRUE
6  1 Hello   FALSE
7  3 Hello    TRUE
8  5 Hello   FALSE
9  7 Hello    TRUE
10 9 Goodbye FALSE

as_tibble() function can be used to coerce a regular data frame to a tibble

In [54]:
library(tibble)
example_data = as_tibble(example_data)
example_data

x y       z    
1  1 Hello    TRUE
2  3 Hello   FALSE
3  5 Hello    TRUE
4  7 Hello   FALSE
5  9 Hello    TRUE
6  1 Hello   FALSE
7  3 Hello    TRUE
8  5 Hello   FALSE
9  7 Hello    TRUE
10 9 Goodbye FALSE

### 3. Programming basics
#### 3.1 Control Flow

##### if/else

In [56]:
x = 1
y = 3
if (x > y) {
    z = x * y
    print("x is larger than y")
} else {
    z = x + 5 * y
    print("x is less than or equal to y")
}
z

[1] "x is less than or equal to y"


[1] 16

Useful function ifelse()

In [57]:
ifelse(4 > 3, 1, 0)

[1] 1

In [58]:
fib = c(1, 1, 2, 3, 5, 8, 13, 21)
ifelse(fib > 6, "Foo", "Bar")

[1] "Bar" "Bar" "Bar" "Bar" "Bar" "Foo" "Foo" "Foo"

##### for loop

In [62]:
x = 11:15
for(i in 1:5){
    if (i %% 2 == 0){
            x[i] = x[i] * 2
        }
    else {
        x[i] = x[i] * 3
    }
}
x

[1] 33 24 39 28 45

#### 3.2 Functions

function_name(arg1 = .., arg2 = .., ...)

In [63]:
standardize = function(x) {
    m = mean(x)
    std = sd(x)
    result = (x - m) / std
    result
}

In [68]:
test_sample = rnorm(n = 10, mean = 2, sd = 5)
test_sample
standardize(test_sample)

[1] -10.2947414   5.2609022   0.1179328   6.3955256   1.3021947  -0.5555928
 [7]  -6.5215424   4.9289400   2.8002003   3.4803263

[1] -2.0496097  0.8524971 -0.1069904  1.0641758  0.1139490 -0.2326454
 [7] -1.3456706  0.7905653  0.3934213  0.5203076

Example: Function to calculate unbiased estimate of population variance, which is sample variance

In [82]:
get_var = function(x, biased = FALSE){
    sum((x - mean(x)) ^ 2) / (length(x) - 1 * !biased)
}

In [85]:
get_var(test_sample)
get_var(test_sample, TRUE)

[1] 28.7309

[1] 25.85781